print("Hello World")
print()
print(2026, 4, 21, sep="/")
print()
print("Line 1\nLine 2\nLine 3")
print()
print("\\")
print()
print("A\tB\tC")
print()
print(input("¿What are you studying?"))
print()
print((input("Write your nombre: ")) + " " + (input("Write your surname: ")))